[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/links"
  to = "/.netlify/functions/links"
  status = 200

[[redirects]]
  from = "/api/links/:id"
  to = "/.netlify/functions/links?id=:id"
  status = 200
