[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# фронт ходит на /api/links -> функция
[[redirects]]
  from = "/api/links"
  to = "/.netlify/functions/links"
  status = 200
